USE_CUDNN := 1
SAVE_FRAME_IN := 1
SAVE_FRAME_OUT :=1

CUDA_DIR := /usr/local/cuda

CUDA_ARCH := -gencode arch=compute_30,code=sm_30 \
             -gencode arch=compute_35,code=sm_35 \
             -gencode arch=compute_50,code=sm_50 \
             -gencode arch=compute_52,code=sm_52 \
			 -gencode arch=compute_53,code=sm_53 \
             -gencode arch=compute_61,code=sm_61

BLAS := open

MYCAFFE_SRC := /home/ubuntu/caffe-ssd/src
MYCAFFE_SRC_BUILD := /home/ubuntu/caffe-ssd/.build_release/src
MYCAFFE_INCLUDE := /home/ubuntu/caffe-ssd/include
MYBUILD_DIR := /home/ubuntu/caffe-ssd/.build_release

PYTHON_INCLUDE := /usr/include/python2.7 \
		/usr/lib/python2.7/dist-packages/numpy/core/include


PYTHON_LIB := /usr/lib
WITH_PYTHON_LAYER := 1

INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/aarch64-linux-gnu/hdf5/serial/

BUILD_DIR := build
Q ?= @
